# Generated by Django 4.2.11 on 2024-06-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_event_description_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='massage',
            new_name='message',
        ),
    ]
