# Generated by Django 4.2.11 on 2024-06-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_rename_massage_event_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='send_massage_time',
            field=models.DateField(),
        ),
    ]
